name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Check style
        run: pnpm run eslint
      - name: Run tests
        run: pnpm run test

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          start: |
            pnpm run build
            pnpm run start-prod
          command: pnpm run test:e2e
          wait-on: http://localhost:5000
      
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: |
          echo "Deploying to Vercel"
          curl ${{ secrets.VERCEL_API_KEY }}
      
      - name: Discord Webhook Notify (Build Failed)
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: 'Build failed! Please check the logs.'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Custom
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            username: CustomUsername
            color: '#ff00aa'
            avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
            description: This is a custom description.
            details: 'Custom details: Somebody set up us the bomb.'
            footer: This is a footer.
            text: This is where text goes.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  
      - name: Discord Webhook Notify (Deployment Success)
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: 'Deployment'
          details: 'Deployment was successful!'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
